@set allusersprofile=c:\programdata
@set appdata=c:\users\???????\appdata\roaming;C:\Users\Анастасия\AppData\Roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-c4gc5q7
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\???????;\Users\Анастасия
@set include=c:\program files (x86)\microsoft visual studio 14.0\vc\include;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\8.1\include\\shared;c:\program files (x86)\windows kits\8.1\include\\um;c:\program files (x86)\windows kits\8.1\include\\winrt
@set lib=c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.10240.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\???????\appdata\local;C:\Users\Анастасия\AppData\Local
@set logonserver=\\desktop-c4gc5q7
@set msbuildloadmicrosofttargetsreadonly=true
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set onedrive=c:\users\???????\onedrive;C:\Users\Анастасия\OneDrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\git\cmd;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\windows\system32\config\systemprofile\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\users\???????\appdata\local\microsoft\windowsapps;c:\program files\opencppcoverage;C:\Users\Анастасия\AppData\Local\Microsoft\WindowsApps
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\???????\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config;C:\Users\Анастасия\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 142 stepping 9, genuineintel
@set processor_level=6
@set processor_revision=8e09
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\08de~1\appdata\local\temp
@set tmp=c:\users\08de~1\appdata\local\temp
@set ucrtversion=10.0.10240.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-c4gc5q7
@set userdomain_roamingprofile=desktop-c4gc5q7
@set username=???????;Анастасия
@set userprofile=c:\users\???????;C:\Users\Анастасия
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 14.0\vc\
@set visualstudiodir=c:\users\???????\documents\visual studio 2015;C:\Users\Анастасия\Documents\Visual Studio 2015
@set visualstudioedition=microsoft visual studio community 2015
@set visualstudioversion=14.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 14.0\
@set vslang=1049
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdklibversion=winv6.3\
@set windowssdkversion=\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\

@call "cl.exe" @"C:\Users\Анастасия\Documents\Visual Studio 2015\Projects\Stack\Stack\main.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1